title: Bodhisattwa Prasad Majumder
description: Data Scientist | Photographer | Philharmonic \n mbodhisattwa@gmail.com
google_analytics: true
show_downloads: false
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
